services:
  postgres:
    container_name: ignite-call
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: ignite-call
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres